---
- name: Install nginx
  dnf:
    name: nginx
    update_cache: yes
- name: Enable nginx
  service:
    name: nginx.service
    state: started
    enabled: yes
- name: Copy web static content
  copy:
    src: "files/web.zip"
    dest: /home/opc
- name: Unzip static content
  ansible.builtin.command: unzip -o /home/opc/web.zip -d /usr/share/nginx/html/
  become: true
  notify: restart nginx
- name: Stop firewalld
  ansible.builtin.command: systemctl stop firewalld
- name: Disable firewalld
  ansible.builtin.command: systemctl disable firewalld