###

POST http://localhost:8080/api/selectai
Content-Type: application/json

{
    "query": "what is the total number of customers"
}

###

POST http://localhost:8080/api/selectai
Content-Type: application/json

{
    "query": "show the top 10 customers who are buying Hardware"
}

###

GET http://localhost:8080/api/selectai/profiles
